import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homepage from '../components/main/Homepage'
import { useGoogleOneTapLogin } from 'react-google-one-tap-login';

export default function Home() {
  
  if(typeof window !=="undefined"){
    useGoogleOneTapLogin({
      onError: error => console.log(error),
      onSuccess: response => console.log(response),
      googleAccountConfigs: {
        client_id: "324680987156-m9o1u2s24kd11b5lqpakasbn3o2dd2ql.apps.googleusercontent.com"
      },
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://accounts.google.com/gsi/client" async defer></script> 
      </Head>
      <main>
          {/* <Homepage/> */}
      </main>
    </div>
  )
}
