import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homepage from '../components/main/Homepage'
import { useGoogleOneTapLogin } from 'react-google-one-tap-login';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello i am index.js</h1>
          {/* <Homepage/> */}
      </main>
    </div>
  )
}
